-- AUTOGENERATED BY SERPANTINUM -- DO NOT EDIT
-- Source of truth: ~/.config/serpantinum/settings.json ("hotkeys" section)
-- Regenerate from the Hotkeys tab of the settings, or: x_keybinds.sh apply

hl.unbind("SUPER + F")
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("termius"), { description = "Termius" })
hl.bind("SUPER + SHIFT + T", hl.dsp.exec_cmd("/opt/tg/Telegram --"), { description = "Telegram" })
hl.bind("SUPER + F", hl.dsp.exec_cmd("brave"), { description = "Brave" })
