package tui

import (
	"fmt"
	"strings"
)

// msgs holds every UI string as {ru, en}. A test checks that both languages
// exist, that they use the same format verbs and that every key used in the
// source is defined.
var msgs = map[string][2]string{
	// header, stepper, units
	"hdr.build":     {"сборка serp-x", "serp-x build"},
	"hdr.installer": {"установщик", "installer"},
	"hdr.lang":      {"язык", "language"},
	"st.check":      {"Проверка", "Check"},
	"st.mode":       {"Режим", "Mode"},
	"st.modules":    {"Модули", "Modules"},
	"st.settings":   {"Настройки", "Settings"},
	"st.summary":    {"Итог", "Summary"},
	"st.install":    {"Установка", "Install"},
	"st.done":       {"Готово", "Done"},
	"u.gib":         {"ГиБ", "GiB"},
	"u.mib":         {"МиБ", "MiB"},
	"u.sec":         {"с", "s"},
	"u.min":         {"мин", "min"},
	"u.mbs":         {"МБ/с", "MB/s"},

	// footer hints
	"f.continue":    {"продолжить", "continue"},
	"f.lang":        {"язык / language", "language / язык"},
	"f.details":     {"подробности", "details"},
	"f.quit":        {"выход", "quit"},
	"f.select":      {"выбор", "select"},
	"f.next":        {"далее", "next"},
	"f.back":        {"назад", "back"},
	"f.toggle":      {"вкл/выкл", "on/off"},
	"f.preset":      {"набор", "preset"},
	"f.cancel":      {"отмена", "cancel"},
	"f.remove_both": {"снять оба", "remove both"},
	"f.field":       {"поле", "field"},
	"f.skip":        {"пропустить", "skip"},
	"f.save_line":   {"сохранить строку в файл", "save the line to a file"},
	"f.start":       {"начать", "start"},
	"f.back_fix":    {"назад и поправить", "back and fix"},
	"f.export":      {"сохранить как my-setup.toml", "save as my-setup.toml"},
	"f.data":        {"мои данные", "my data"},
	"f.log":         {"лог", "log"},
	"f.hide_log":    {"скрыть лог", "hide log"},
	"f.focus":       {"фокус", "focus"},
	"f.pause":       {"пауза", "pause"},
	"f.resume":      {"продолжить", "resume"},
	"f.abort_safe":  {"прервать (безопасно)", "abort (safe)"},
	"f.choose":      {"выбор кнопки", "choose a button"},
	"f.do":          {"выполнить", "do it"},
	"f.full_log":    {"весь лог", "full log"},
	"f.yes":         {"да", "yes"},
	"f.no":          {"нет", "no"},
	"f.run":         {"выполнить", "run"},

	// I1
	"i1.title":    {"Установщик сборки Serpantinum", "Serpantinum build installer"},
	"i1.intro":    {"Оболочка Serpantinum (ilyamiro) + модули сборки serp-x: горячие клавиши, обновления, VPN, серверы, Commands.", "Serpantinum shell (ilyamiro) + serp-x build modules: hotkeys, updates, VPN, servers, Commands."},
	"i1.lang":     {"Язык / Language", "Language / Язык"},
	"i1.f2":       {"сменить когда угодно", "change any time"},
	"i1.next":     {"Что дальше", "What next"},
	"i1.n1":       {"выбрать режим", "choose a mode"},
	"i1.n2":       {"отметить модули", "pick the modules"},
	"i1.n3":       {"ответить на вопросы (все до начала)", "answer the questions (all before the start)"},
	"i1.n4":       {"уйти пить чай: установка идёт сама, ~10-20 минут", "go and have tea: the install runs on its own, ~10-20 minutes"},
	"i1.check":    {"Проверка системы", "System check"},
	"i1.checking": {"проверяю систему...", "checking the system..."},
	"i1.total":    {"Итог:", "Result:"},
	"i1.can":      {"можно продолжать", "ready to go"},
	"i1.warns":    {"предупреждений: %d", "warnings: %d"},
	"i1.blocked":  {"продолжать нельзя, проблем: %d", "cannot continue, problems: %d"},

	// I2
	"i2.found":           {"Найдена установленная сборка %s", "Installed build found: %s"},
	"i2.since":           {"поставлена %s · модулей: %d", "installed %s · modules: %d"},
	"i2.safe":            {"Данные (настройки, команды, заметки, ключи) не пропадут: перед изменениями будет бэкап.", "Your data (settings, commands, notes, keys) is safe: a backup is made before any change."},
	"i2.upstream":        {"Найдена оригинальная установка Serpantinum %s", "Original Serpantinum %s found"},
	"i2.upstream2":       {"Настройки сохраню в бэкап; перейдём на serp-x.", "Settings go to a backup; we switch to serp-x."},
	"i2.legacy":          {"Найдена старая установка (imperative-dots)", "Old installation (imperative-dots) found"},
	"i2.nothing":         {"Установки не найдено, но есть незавершённый запуск.", "No installation found, but an unfinished run exists."},
	"i2.what":            {"Что сделать?", "What to do?"},
	"i2.will":            {"Что произойдёт:", "What will happen:"},
	"i2.unfinished":      {"Есть незавершённый запуск?", "Unfinished run?"},
	"i2.yes":             {"да", "yes"},
	"i2.no":              {"нет", "no"},
	"i2.resume":          {"Продолжить прерванную установку", "Continue the interrupted install"},
	"i2.resume.sub":      {"выберу то же и продолжу с места остановки", "same choices, continues where it stopped"},
	"i2.resume.what":     {"Журнал сохранён: готовые шаги пропускаются, установка идёт с первого незавершённого. Модули и вопросы нужно подтвердить снова (секреты не хранятся в журнале).", "The journal is kept: finished steps are skipped and the run continues from the first unfinished one. Confirm modules and questions again (secrets are not kept in the journal)."},
	"i2.resume.time":     {"Быстрее обычной установки.", "Faster than a fresh install."},
	"i2.title_resume":    {"Продолжить", "Continue"},
	"i2.repair":          {"Починить / переустановить", "Repair / reinstall"},
	"i2.repair.sub":      {"проверю файлы, хуки, службы, пакеты", "checks files, hooks, services, packages"},
	"i2.repair.what":     {"1. Бэкап данных\n2. Проверка файлов по хэшам\n3. Хуки в файлах upstream\n4. Службы\n5. Недостающие пакеты", "1. Data backup\n2. File check by hash\n3. Hooks in upstream files\n4. Services\n5. Missing packages"},
	"i2.repair.time":     {"Займёт пару минут. Без перезагрузки.", "Takes a couple of minutes. No reboot."},
	"i2.title_repair":    {"Починить / переустановить", "Repair / reinstall"},
	"i2.modules":         {"Изменить модули", "Change modules"},
	"i2.modules.sub":     {"добавить или убрать", "add or remove"},
	"i2.modules.what":    {"Покажу список модулей. Добавлю то, что отметишь, и уберу то, что снимешь. Остальное не трогаю.", "Shows the module list. Adds what you tick and removes what you untick. The rest stays untouched."},
	"i2.modules.time":    {"Зависит от выбора.", "Depends on the choice."},
	"i2.title_modules":   {"Изменить модули", "Change modules"},
	"i2.uninstall":       {"Удалить сборку", "Uninstall"},
	"i2.uninstall.sub":   {"оболочку и службы; данные оставлю", "shell and services; your data stays"},
	"i2.uninstall.what":  {"Удалю оболочку, ссылки, службы и root-файлы модулей. Настройки, команды, заметки и ключи останутся (можно удалить и их).", "Removes the shell, links, services and module root files. Settings, commands, notes and keys stay (you can remove them too)."},
	"i2.uninstall.time":  {"Займёт около минуты.", "Takes about a minute."},
	"i2.title_uninstall": {"Удалить", "Uninstall"},
	"i2.reinstall":       {"Установить начисто", "Clean install"},
	"i2.reinstall.sub":   {"как с нуля; бэкап + восстановление", "like from scratch; backup + restore"},
	"i2.reinstall.what":  {"Бэкап данных, полная перезаливка кода и root-слоя, затем восстановление данных. Выберешь модули заново.", "Data backup, full redeploy of the code and root layer, then a data restore. You pick the modules again."},
	"i2.reinstall.time":  {"Как обычная установка.", "Same as a regular install."},
	"i2.title_reinstall": {"Установить начисто", "Clean install"},
	"i2.install":         {"Установить serp-x", "Install serp-x"},
	"i2.install.sub":     {"поверх найденной установки", "over the installation found"},
	"i2.install.what":    {"Настройки найденной установки уходят в бэкап, затем ставится сборка serp-x с выбранными модулями.", "The settings of the installation found go to a backup, then the serp-x build is installed with the chosen modules."},
	"i2.install.time":    {"Около 10-20 минут.", "About 10-20 minutes."},
	"i2.title_install":   {"Установить serp-x", "Install serp-x"},

	// I3
	"i3.preset":      {"Набор:", "Preset:"},
	"i3.p_full":      {"Полный", "Full"},
	"i3.p_minimal":   {"Минимальный", "Minimal"},
	"i3.p_custom":    {"Свой", "Custom"},
	"i3.title":       {"Модули", "Modules"},
	"i3.g_core":      {"Обязательно", "Required"},
	"i3.g_build":     {"Возможности сборки", "Build features"},
	"i3.g_system":    {"Из upstream и система", "Upstream and system"},
	"i3.gpu_found":   {"найдена видеокарта", "GPU found"},
	"i3.auto":        {"авто", "auto"},
	"i3.packages":    {"Пакеты:", "Packages:"},
	"i3.hint":        {"Пробел отмечает модуль. Зависимости включаются сами.", "Space ticks a module. Dependencies are added automatically."},
	"i3.core_locked": {"Оболочка обязательна: её нельзя снять.", "The shell is required: it cannot be removed."},
	"i3.auto_on":     {"Включено автоматически: %s (нужно для выбранного).", "Enabled automatically: %s (needed by your choice)."},
	"i3.cascade_t":   {"%s нужен другим", "%s is needed by others"},
	"i3.cascade":     {"Вместе с ним отключится: %s.", "This also turns off: %s."},
	"i3.remove_both": {"Снять оба", "Remove both"},
	"i3.cancel":      {"Отмена", "Cancel"},
	"i3.both_off":    {"Снято: %s.", "Removed: %s."},
	"i3.conflict":    {"%s конфликтует с %s: сначала сними один из них.", "%s conflicts with %s: remove one of them first."},
	"i3.total":       {"Всего", "Total"},
	"i3.dl":          {"Скачать", "Download"},
	"i3.disk":        {"На диске", "On disk"},
	"i3.time":        {"Время", "Time"},
	"i3.at_speed":    {"при %s МБ/с", "at %s MB/s"},

	// wizard
	"w.step":            {"Настройка %d из %d", "Setting %d of %d"},
	"w.empty":           {"(пусто)", "(empty)"},
	"w.fmt_ok":          {"формат верный", "format looks right"},
	"w.fmt_bad":         {"формат не похож", "format looks wrong"},
	"w.check_later":     {"запросом проверю после установки", "I will test it with a request after the install"},
	"w.bad_format":      {"Поле «%s»: формат не похож. Поправь или пропусти шаг.", "Field \"%s\": wrong format. Fix it or skip the step."},
	"w.need_value":      {"Поле «%s» не должно быть пустым.", "Field \"%s\" must not be empty."},
	"w.safety":          {"Безопасность", "Security"},
	"w.safety.text":     {"Секрет сохранится в ~/.config/serpantinum/secrets/ с правами 600: читаешь только ты. В лог и в бэкап (без пароля) он не попадает. Пропуск ничего не ломает.", "The secret is stored in ~/.config/serpantinum/secrets/ with mode 600: only you can read it. It never goes to the log or to a backup. Skipping breaks nothing."},
	"w.auth_path":       {"~/serp-authorized_keys.txt", "~/serp-authorized_keys.txt"},
	"w.saved":           {"Строка сохранена: %s", "Line saved: %s"},
	"w.save_fail":       {"Не удалось сохранить: %s", "Could not save: %s"},
	"w.ssh_title":       {"SSH-ключ только для виджета", "SSH key for the widget only"},
	"w.ssh_gen":         {"создаю ключ ed25519...", "creating the ed25519 key..."},
	"w.ssh_ok":          {"Создан ключ ed25519 %s", "ed25519 key created: %s"},
	"w.ssh_fail":        {"Ключ не создан: %s", "Key was not created: %s"},
	"w.ssh_add":         {"На каждом сервере добавь в ~serp/.ssh/authorized_keys ровно эту строку:", "On every server add exactly this line to ~serp/.ssh/authorized_keys:"},
	"w.ssh_allow":       {"Ключ может запускать только разрешённые команды (allowlist), без shell и пробросов:", "The key can only run allowed commands (allowlist), no shell, no forwarding:"},
	"w.ssh_easy":        {"Проще: после установки нажми «Подключить сервер» в виджете.", "Easier: after the install press \"Connect server\" in the widget."},
	"b.save":            {"Сохранить строку в %s", "Save the line to %s"},
	"b.check":           {"Проверить ключ", "Check the key"},
	"b.skip":            {"Пропустить - настрою позже", "Skip - I will set it up later"},
	"b.next":            {"Далее", "Next"},
	"b.back":            {"Назад", "Back"},
	"ch.ru":             {"русский", "Russian"},
	"ch.en":             {"English", "English"},
	"ch.ru-direct":      {"Россия напрямую", "Russia direct"},
	"ch.all":            {"Всё через VPN", "Everything via VPN"},
	"w.title.core":      {"Язык оболочки", "Shell language"},
	"w.intro.core":      {"На каком языке показывать оболочку Serpantinum. По умолчанию - язык установщика.", "Which language the Serpantinum shell uses. By default - the installer language."},
	"w.title.ai-gemini": {"ИИ: ключ Gemini", "AI: Gemini key"},
	"w.intro.ai-gemini": {"Нужен для перевода списка изменений и узла «Gemini» в Commands. Можно пропустить - ключ вводится потом в Настройки - Обновления.", "Used to translate the changelog and for the Gemini node in Commands. You can skip it - the key can be entered later in Settings - Updates."},
	"w.title.servers":   {"Виджет серверов: панель и SSH-ключ", "Servers widget: panel and SSH key"},
	"w.intro.servers":   {"Адрес панели Remnawave и API-токен. Сохраняются в ~/.config/serpantinum/secrets/ (600). Пропустить можно.", "Remnawave panel address and API token. Stored in ~/.config/serpantinum/secrets/ (600). You can skip it."},
	"w.title.vpn":       {"VPN: подписка", "VPN: subscription"},
	"w.intro.vpn":       {"Ссылка на подписку и режим. Служба ставится выключенной: не включай её вместе с другим VPN.", "Subscription link and mode. The service is installed disabled: do not run it together with another VPN."},
	"w.title.tools":     {"Пипетка и заметки", "Color picker and notes"},
	"w.intro.tools":     {"Куда складывать быстрые заметки.", "Where quick notes are kept."},
	"w.title.commands":  {"Commands", "Commands"},
	"w.intro.commands":  {"Демон автоматизаций и примеры из галереи.", "The automation daemon and gallery examples."},

	// I6
	"s.ready.install":     {"Всё готово к установке. Дальше вопросов не будет - можно отойти.", "Everything is ready to install. No more questions - you can step away."},
	"s.ready.resume":      {"Всё готово продолжить установку. Готовые шаги будут пропущены.", "Ready to continue. Finished steps will be skipped."},
	"s.ready.modules":     {"Всё готово: применю изменения модулей.", "Ready: the module changes will be applied."},
	"s.ready.repair":      {"Всё готово: проверю и починю установку.", "Ready: the installation will be checked and repaired."},
	"s.ready.uninstall":   {"Всё готово к удалению сборки.", "Ready to uninstall the build."},
	"s.will_install":      {"Будет установлено · %d", "Will be installed · %d"},
	"s.will_do.repair":    {"Что сделаю", "What I will do"},
	"s.will_do.uninstall": {"Что удалю", "What I will remove"},
	"s.will_do.install":   {"Что сделаю", "What I will do"},
	"s.will_do.modules":   {"Что сделаю", "What I will do"},
	"s.not_install":       {"Не ставлю:", "Not installing:"},
	"s.settings":          {"Настройки", "Settings"},
	"s.lang":              {"Язык", "Language"},
	"s.skipped":           {"пропущено", "skipped"},
	"s.key_set":           {"ключ задан", "key set"},
	"s.proxy":             {"с прокси", "with proxy"},
	"s.no_proxy":          {"без прокси", "no proxy"},
	"s.set":               {"задан", "set"},
	"s.ssh":               {"SSH-ключ", "SSH key"},
	"s.created":           {"создан", "created"},
	"s.none":              {"нет", "none"},
	"s.notes":             {"Заметки", "Notes"},
	"s.daemon":            {"демон", "daemon"},
	"s.examples":          {"примеры", "examples"},
	"s.backup":            {"Бэкап", "Backup"},
	"s.backup_before":     {"сделаю перед началом", "made before the start"},
	"s.restore":           {"Восстановить", "Restore"},
	"s.later":             {"Настроить позже:", "Set up later:"},
	"s.root":              {"С правами root (sudo) изменю", "With root rights (sudo) I will change"},
	"s.no_root":           {"ничего", "nothing"},
	"s.total":             {"Итого", "Total"},
	"s.planning":          {"считаю план...", "building the plan..."},
	"s.plan_fail":         {"План не построен: %s", "The plan could not be built: %s"},
	"s.remove_data":       {"Удалить и мои данные (d)", "Remove my data too (d)"},
	"s.data_note":         {"Настройки, команды, заметки и ключи сохранятся, если не отметить. Перед удалением данных будет бэкап.", "Settings, commands, notes and keys stay unless ticked. A backup is made before data is removed."},
	"s.data_warn":         {"Данные будут удалены после бэкапа.", "The data will be removed after a backup."},
	"s.repair_note":       {"Данные не затрагиваются. Изменённые тобой файлы покажу списком.", "Your data is untouched. Files you changed are listed."},
	"s.exported":          {"Настройки сохранены: %s", "Settings saved: %s"},
	"b.start.install":     {"Начать установку", "Start the install"},
	"b.start.modules":     {"Применить", "Apply"},
	"b.start.repair":      {"Начать ремонт", "Start the repair"},
	"b.start.uninstall":   {"Удалить", "Uninstall"},

	// progress
	"p.step":        {"Шаг %d из %d", "Step %d of %d"},
	"p.elapsed":     {"прошло", "elapsed"},
	"p.left":        {"осталось", "left"},
	"p.eta_hint":    {"оценка уточняется по скорости сети", "the estimate improves with the network speed"},
	"p.paused":      {"пауза: следующий шаг не начнётся", "paused: the next step will not start"},
	"p.steps":       {"Шаги", "Steps"},
	"p.now":         {"Сейчас", "Now"},
	"p.now.generic": {"%s...", "%s..."},
	"p.got":         {"Скачано", "Downloaded"},
	"p.of":          {"%s из %s МиБ", "%s of %s MiB"},
	"p.speed":       {"Скорость", "Speed"},
	"p.file":        {"Файл", "File"},
	"p.away":        {"Можно отойти: вопросов больше не будет. Если пропадёт свет - запусти снова, продолжу с этого шага.", "You can step away: there will be no more questions. If the power goes out - run again, it continues from this step."},
	"p.logfile":     {"Лог:", "Log:"},
	"p.log":         {"Лог", "Log"},
	"p.log_help":    {"L - скрыть, стрелки - листать", "L - hide, arrows - scroll"},
	"p.skipped":     {"пропущено", "skipped"},
	"p.failed":      {"ошибка", "failed"},
	"q.title":       {"Прервать?", "Abort?"},
	"q.text":        {"Прервать безопасно: журнал сохранится, повторный запуск продолжит с этого места.", "Safe to abort: the journal is kept and the next run continues from here."},
	"q.abort":       {"Прервать", "Abort"},
	"q.stay":        {"Продолжить", "Keep going"},

	// error modal
	"e.title":        {"Не получилось", "It did not work"},
	"e.failed":       {"Шаг не удался: %s", "Step failed: %s"},
	"e.did":          {"Что делал: %s.", "What I was doing: %s."},
	"e.what":         {"Что случилось: %s", "What happened: %s"},
	"e.hint.net":     {"нет ответа от сети. Похоже на сеть, а не на ошибку в системе.", "no answer from the network. It looks like the network, not a system error."},
	"e.hint.keys":    {"проблема с ключами пакетов (PGP). Помогает обновление archlinux-keyring.", "a package key (PGP) problem. Updating archlinux-keyring usually helps."},
	"e.hint.disk":    {"не хватает места на диске.", "not enough disk space."},
	"e.hint.lock":    {"pacman занят другим процессом (db.lck).", "pacman is busy with another process (db.lck)."},
	"e.hint.generic": {"команда завершилась с ошибкой, подробности ниже.", "a command failed, details below."},
	"e.options":      {"Варианты:", "Options:"},
	"e.retry":        {"Повторить", "Retry"},
	"e.retry.d":      {"ещё раз (бывает, помогает через минуту)", "once more (sometimes helps after a minute)"},
	"e.skip":         {"Пропустить %s", "Skip %s"},
	"e.skip.d":       {"доустановлю остальное; %s добавишь позже", "the rest is installed; add %s later"},
	"e.abort":        {"Прервать", "Abort"},
	"e.abort.d":      {"ничего не сломается, повторный запуск продолжит", "nothing breaks, the next run continues"},
	"e.b.retry":      {"Повторить", "Retry"},
	"e.b.skip":       {"Пропустить %s", "Skip %s"},
	"e.b.abort":      {"Прервать", "Abort"},
	"e.full_log":     {"весь лог", "full log"},

	// finish
	"fin.done_in.install":   {"Готово за %s", "Done in %s"},
	"fin.done_in.modules":   {"Готово за %s", "Done in %s"},
	"fin.done_in.repair":    {"Починено за %s", "Repaired in %s"},
	"fin.done_in.uninstall": {"Удалено за %s", "Uninstalled in %s"},
	"fin.build":             {"сборка serp-x %s", "serp-x build %s"},
	"fin.failed":            {"Установка не завершена", "The run did not finish"},
	"fin.failed_text":       {"Журнал сохранён, ничего не сломано. Можно продолжить с того же места.", "The journal is kept, nothing is broken. You can continue from the same place."},
	"fin.state":             {"Состояние", "State"},
	"fin.result":            {"Результат", "Result"},
	"fin.installed":         {"Установлено · %d", "Installed · %d"},
	"fin.mode.repair":       {"установка проверена и починена", "installation checked and repaired"},
	"fin.mode.uninstall":    {"сборка удалена, данные на месте", "the build is removed, your data is kept"},
	"fin.attention":         {"Обрати внимание", "Please note"},
	"fin.skipped":           {"%s пропущен", "%s skipped"},
	"fin.add_later":         {"добавить:", "add it:"},
	"fin.later":             {"Настроить позже:", "Set up later:"},
	"fin.restored":          {"Данные восстановлены", "Data restored"},
	"fin.retype":            {"Введи заново (секреты не входят в бэкап):", "Enter again (secrets are not part of a backup):"},
	"fin.reboot":            {"NVIDIA: нужна перезагрузка", "NVIDIA: a reboot is needed"},
	"fin.nothing":           {"Всё в порядке.", "All good."},
	"fin.resume_hint":       {"Чтобы продолжить:", "To continue:"},
	"fin.files":             {"Файлы", "Files"},
	"fin.log":               {"Лог", "Log"},
	"fin.backup":            {"Бэкап", "Backup"},
	"fin.config":            {"Конфиг", "Config"},
	"fin.config_note":       {"для быстрой переустановки", "for a quick reinstall"},
	"fin.b.reboot":          {"Перезагрузить", "Reboot"},
	"fin.b.reboot_nv":       {"Перезагрузить (нужно для NVIDIA)", "Reboot (needed for NVIDIA)"},
	"fin.b.hyprland":        {"Запустить Hyprland", "Start Hyprland"},
	"fin.b.exit":            {"Выйти в консоль", "Exit to the console"},
}

// tr translates key into lang (ru|en), formatting with a when given.
func tr(lang, key string, a ...any) string {
	v, ok := msgs[key]
	if !ok {
		return key
	}
	s := v[0]
	if lang == "en" {
		s = v[1]
	}
	if len(a) == 0 || !strings.Contains(s, "%") {
		return s
	}
	return fmt.Sprintf(s, a...)
}
