import QtQuick
import "EditorLogic.js" as EL
import "DebugLogic.js" as DL
import "data.js" as D

// Plain `qml6` test of EditorLogic.js (no Quickshell needed). data.js is generated by editor_logic_test.sh from the REAL
// CLI (ui-schema + ui-get of the fixture commands), so the parity check compares the JS view builder with uiview.py.
Item {
    property int passed: 0
    property int failed: 0
    readonly property var cat: EL.indexCatalog(D.schema.catalog)

    function ok(cond, msg) { if (cond) passed++; else { failed++; console.log("FAIL " + msg); } }
    function eq(a, b, msg) { var sa = JSON.stringify(a), sb = JSON.stringify(b); ok(sa === sb, msg + "\n   got  " + sa + "\n   want " + sb); }
    function wires(cmd, from, pin) { return cmd.wires.filter(function (w) { return w.from[0] === from && w.from[1] === pin; }); }
    function findInput(cmd, nodeId, pin) { return cmd.wires.filter(function (w) { return w.to[0] === nodeId && w.to[1] === pin; }); }
    function viewNode(view, id) { for (var i = 0; i < view.nodes.length; i++) if (view.nodes[i].id === id) return view.nodes[i]; return null; }

    function parity() {
        var names = Object.keys(D.gets), n = 0;
        for (var k = 0; k < names.length; k++) {
            var py = D.gets[names[k]], js = EL.buildView(py.command, cat, "ru", null);
            eq(js.nodes.length, py.nodes.length, names[k] + ": node count");
            for (var i = 0; i < py.nodes.length; i++) {
                var a = py.nodes[i], b = viewNode(js, a.id);
                if (b === null) { ok(false, names[k] + ": missing node " + a.id); continue; }
                var keys = Object.keys(a);
                for (var j = 0; j < keys.length; j++) {
                    n++;
                    eq(b[keys[j]], a[keys[j]], names[k] + "/" + a.id + "." + keys[j]);
                }
            }
            eq(js.wires, py.wires, names[k] + ": wires");
            eq(js.comments, py.comments, names[k] + ": comments");
            eq(js.bounds, py.bounds, names[k] + ": bounds");
        }
        ok(n > 100, "parity compared a meaningful amount of fields (" + n + ")");
    }

    function ops() {
        var base = D.gets.headphones.command;
        // add a node: next free id, snapped position, empty props
        var r = EL.addNode(base, cat["action.notify@1"], 1233, 417);
        eq(r.id, "n7", "addNode id");
        eq(EL.findNode(r.cmd, "n7").pos, [1230, 420], "addNode snaps to the grid");
        eq(base.nodes.length, 6, "addNode does not mutate its input");

        // exec output has one wire: connecting replaces it (Unreal-like)
        var c1 = EL.connect(r.cmd, cat, ["n2", "exec_out"], ["n7", "exec_in"]);
        eq(wires(c1, "n2", "exec_out").map(function (w) { return w.to[0]; }), ["n7"], "exec fan-out is replaced");
        // a data input has one wire too
        var c2 = EL.connect(c1, cat, ["n1", "device"], ["n7", "title"]);
        var c3 = EL.connect(c2, cat, ["n1", "device"], ["n7", "body"]);
        eq(findInput(c3, "n7", "title").length, 1, "one wire per input");
        // wiring an input drops its literal
        var lit = EL.setProp(c1, "n7", "title", "Привет");
        eq(EL.findNode(lit, "n7").props.title, "Привет", "setProp");
        var wired = EL.connect(lit, cat, ["n1", "device"], ["n7", "title"]);
        ok(EL.findNode(wired, "n7").props.title === undefined, "a wired input no longer carries a literal");
        eq(viewNode(EL.buildView(lit, cat, "ru", null), "n7").ins[1].v, "Привет", "literal is shown in the view");
        ok(viewNode(EL.buildView(EL.setProp(lit, "n7", "title", undefined), cat, "ru", null), "n7").ins[1].v === undefined, "removing the literal clears the chip");

        // instant checks
        eq(EL.canConnect(c1, cat, ["n2", "exec_out"], ["n7", "exec_in"]).ok, true, "exec -> exec is fine");
        var bad = EL.canConnect(c1, cat, ["n1", "exec"], ["n7", "title"]);
        eq([bad.ok, bad.code], [false, "exec_data"], "exec -> data rejected");
        bad = EL.canConnect(c1, cat, ["n1", "device"], ["n7", "exec_in"]);
        eq([bad.ok, bad.code], [false, "exec_data"], "data -> exec rejected");
        bad = EL.canConnect(c1, cat, ["n2", "exec_out"], ["n2", "exec_in"]);
        eq(bad.code, "self", "self connection rejected");
        bad = EL.canConnect(c1, cat, ["n2", "exec_out"], ["nope", "exec_in"]);
        eq(bad.code, "missing", "missing node");
        // exec cycle: n2 -> n7 exists, n7 -> n2 would close it
        bad = EL.canConnect(c1, cat, ["n7", "exec_out"], ["n2", "exec_in"]);
        eq([bad.ok, bad.code], [false, "cycle"], "exec cycle rejected");
        ok(bad.reason.indexOf("Для каждого") >= 0, "cycle message points to «Для каждого»");

        // type mismatch with a converter fix: int (shell exit code) -> text (notify title)
        var s = EL.addNode(base, cat["action.shell@1"], 100, 500), sid = s.id;
        var n = EL.addNode(s.cmd, cat["action.notify@1"], 600, 500), nid = n.id;
        var mm = EL.canConnect(n.cmd, cat, [sid, "exit_code"], [nid, "title"]);
        eq([mm.ok, mm.code], [false, "type"], "int -> text is a type error");
        eq(mm.reason, "Этому входу нужен текст, а подключено число", "type error message");
        eq(mm.fix.node_type, "convert.to_text@1", "a converter is offered");
        eq(EL.canConnect(n.cmd, cat, [sid, "stdout"], [nid, "title"]).ok, true, "text -> text");
        eq(EL.canConnect(n.cmd, cat, [sid, "exit_code"], [nid, "body"]).code, "type", "int -> text body also rejected");
        // implicit int -> float is allowed (delay.seconds is float)
        var d = EL.addNode(n.cmd, cat["logic.delay@1"], 900, 500);
        eq(EL.canConnect(d.cmd, cat, [sid, "exit_code"], [d.id, "seconds"]).ok, true, "int -> float is implicit");

        // applying the fix (forced wire as the engine reports it)
        var forced = EL.connect(n.cmd, cat, [sid, "exit_code"], [nid, "title"]);
        var fx = EL.applyFix(forced, cat, { kind: "insert_converter", node_type: "convert.to_text@1", wire: [sid, "exit_code", nid, "title"] });
        eq(fx.id, "n" + (parseInt(nid.slice(1), 10) + 1), "converter id");
        eq(findInput(fx.cmd, nid, "title").map(function (w) { return w.from[0]; }), [fx.id], "the target is fed by the converter");
        eq(findInput(fx.cmd, fx.id, "value").map(function (w) { return w.from; }), [[sid, "exit_code"]], "the converter is fed by the source");
        eq(wires(fx.cmd, sid, "exit_code").length, 1, "the old direct wire is gone");

        // data cycle through generics-free converters: to_text.text -> to_int.text, to_int.value -> to_text.value
        var t1 = EL.addNode(base, cat["convert.to_text@1"], 100, 700), t2 = EL.addNode(t1.cmd, cat["convert.to_int@1"], 400, 700);
        var cyc = EL.connect(t2.cmd, cat, [t1.id, "text"], [t2.id, "text"]);
        eq(EL.canConnect(cyc, cat, [t2.id, "value"], [t1.id, "value"]).code, "cycle", "data cycle rejected");

        // delete: node + its wires, selected wire only, comment
        var sel = { nodes: { n2: true }, wires: {}, comments: {} };
        var del = EL.deleteItems(base, sel);
        ok(EL.findNode(del, "n2") === null, "node deleted");
        ok(del.wires.every(function (w) { return w.from[0] !== "n2" && w.to[0] !== "n2"; }), "its wires are deleted too");
        var key = EL.wireKey(base.wires[0]);
        var del2 = EL.deleteItems(base, { nodes: {}, wires: (function () { var o = {}; o[key] = true; return o; })(), comments: {} });
        eq(del2.wires.length, base.wires.length - 1, "a single wire is deleted");
        eq(EL.disconnect(base, key).wires.length, base.wires.length - 1, "disconnect by key");
        var del3 = EL.deleteItems(base, { nodes: {}, wires: {}, comments: { c1: true } });
        eq((del3.comments || []).length, 0, "comment deleted (implicit id c1)");

        // move: only selected, snapped
        var mv = EL.moveItems(base, { nodes: { n1: true }, comments: {} }, 13, -7);
        eq(EL.findNode(mv, "n1").pos, [60, 50], "moveItems snaps");
        eq(EL.findNode(mv, "n2").pos, EL.findNode(base, "n2").pos, "unselected nodes stay");

        // comments
        var ac = EL.addComment(base, 105, 205);
        eq(ac.id, "c2", "second comment id");
        var sc = EL.setComment(ac.cmd, "c1", { title: "Новый заголовок", color: EL.nextCommentColor("#f9e2af") });
        eq([sc.comments[0].title, sc.comments[0].color], ["Новый заголовок", "#a6e3a1"], "setComment + colour cycle");
        eq(EL.nextCommentColor("#cba6f7"), "", "colour cycle wraps");

        // copy / paste keeps internal wires only and gets fresh ids
        var clip = EL.copySelection(base, { nodes: { n2: true, n3: true, n4: true }, wires: {}, comments: {} });
        eq(clip.nodes.length, 3, "copy: nodes");
        eq(clip.wires.length, 2, "copy: only wires inside the selection (n2->n3, n3->n4)");
        var pr = EL.paste(base, clip, 40, 40);
        eq(Object.keys(pr.nodes).sort(), ["n7", "n8", "n9"], "paste: fresh ids");
        eq(pr.cmd.wires.length, base.wires.length + 2, "paste: wires copied");
        eq(EL.findNode(pr.cmd, "n7").pos, [440, 90], "paste: offset and snap");

        // view: issues mark pins and nodes
        var issues = EL.indexIssues({ errors: [{ level: "error", code: "missing_input", node: "n2", pin: "device", message: "нет" }], warnings: [{ level: "warning", node: "n3", code: "no_undo" }] });
        var v = EL.buildView(base, cat, "ru", issues);
        eq(viewNode(v, "n2").err, 1, "node error count");
        eq(viewNode(v, "n3").warn, 1, "node warning count");
        eq(viewNode(v, "n2").ins[1].bad, true, "pin marked bad");
        ok(viewNode(v, "n1").err === undefined, "clean nodes carry no markers");

        // palette search
        var hits = EL.searchCatalog(cat, "установить громк", 10);
        eq(hits[0].id, "action.volume_set", "search: title match first");
        ok(EL.searchCatalog(cat, "громк уст", 10).length >= 1, "search: several words");
        eq(EL.searchCatalog(cat, "zzzzzz", 10).length, 0, "search: nothing found");
        ok(EL.searchCatalog(cat, "", 5).length === 5, "search: empty query lists nodes up to the limit");
        ok(EL.searchCatalog(cat, "notify", 5).some(function (e) { return e.id === "action.notify"; }), "search: by id / English words");
        // pin-driven palette: nodes that accept a dragged text output / produce an int
        var txt = EL.entriesFor(cat, "text", true).map(function (e) { return e.entry.id; });
        ok(txt.indexOf("action.notify") >= 0 && txt.indexOf("action.clipboard_set") >= 0, "entriesFor(text out) lists text consumers");
        ok(txt.indexOf("logic.delay") < 0, "entriesFor(text out) skips float-only consumers");
        var execIn = EL.entriesFor(cat, "exec", true).map(function (e) { return e.entry.id; });
        ok(execIn.indexOf("action.notify") >= 0 && execIn.indexOf("convert.to_text") < 0, "exec output feeds exec inputs only");
        ok(EL.entriesFor(cat, "int", false).some(function (e) { return e.entry.id === "convert.to_int"; }), "an int input can be fed by to_int");

        // type helpers
        eq([EL.compatible("int", "float"), EL.compatible("float", "int"), EL.compatible("text", "any"), EL.compatible("any", "text")], [true, false, true, false], "compatible");
        eq(EL.compatible("list<text>", "list<any>"), true, "list<T> -> list<any>");
        eq(EL.typeName("list<int>", "ru"), "список (число)", "list type name");
        eq(EL.fmtValue(40.0, "ru"), "40", "numbers without a trailing .0");
        eq(EL.fmtValue("очень длинная строка значения", "ru"), "очень длинная стр…", "long values are cut like in the engine");
    }

    function fnCollapse() {
        var evening = D.gets.evening.command;
        var sel = { n2: true, n3: true, n4: true };
        var r = EL.collapseSelection(evening, cat, sel, { name: "Тихий вечер", description: "d" });
        ok(r.ok, "collapse ok");
        eq([r.fn.exec, r.fn.inputs.length, r.fn.outputs.length, r.count], [true, 1, 0, 3], "collapse: one numeric literal becomes the only input");
        eq(r.fn.inputs[0], { id: "percent", type: "int", label: "Яркость, %", "default": 30 }, "collapse: the literal pin with its default (C5)");
        eq(r.fn.nodes.map(function (n) { return n.id; }), ["fn_in", "n2", "n3", "n4", "fn_out"], "collapse: interface nodes around the group");
        eq(r.fn.wires.map(EL.wireKey).sort(), ["fn_in:exec>n2:exec_in", "fn_in:percent>n4:percent", "n2:exec_out>n3:exec_in", "n3:exec_out>n4:exec_in"], "collapse: inner wires + entry");
        eq(EL.findNode({ nodes: r.fn.nodes }, "n2").pos, [340, 60], "collapse: positions normalised");
        var app = EL.applyCollapse(evening, r.plan, "fn.tihij@1");
        eq(app.cmd.nodes.map(function (n) { return n.id; }), ["n1", app.id], "apply: the group is replaced by ONE call node");
        eq(EL.findNode(app.cmd, app.id).props, { percent: 30 }, "apply: the literal is kept on the call node");
        eq(app.cmd.wires.map(EL.wireKey), ["n1:exec>" + app.id + ":exec_in"], "apply: the entry wire re-joined");
        eq(evening.nodes.length, 4, "collapse does not mutate the input");
        // view of the call node: pins from the catalogue, footer note like C5
        var ent = JSON.parse(JSON.stringify(cat["fn.quiet-evening@1"]));
        ok(!!ent, "catalogue has the library function");
        var cat2 = EL.indexCatalog(D.schema.catalog); cat2["fn.tihij@1"] = ent;
        var v = viewNode(EL.buildView(app.cmd, cat2, "ru", null), app.id);
        eq(v.cat, "function", "call node has the function category");
        eq(v.note, "функция · 3 узл. внутри · открыть ↗", "call node footer note");
        // expand = inverse: same chain and literal back, ids fresh
        var back = EL.expandCall(app.cmd, cat2, app.id, r.fn);
        ok(back.ok, "expand ok");
        eq(back.cmd.nodes.map(function (n) { return n.type; }), ["event.sunset@1", "action.night_filter@1", "action.dark_theme@1", "action.brightness@1"], "expand: nodes back in order");
        eq(back.cmd.wires.map(EL.wireKey).sort(), ["n1:exec>n2:exec_in", "n2:exec_out>n3:exec_in", "n3:exec_out>n4:exec_in"], "expand: wires re-joined");
        eq(EL.findNode(back.cmd, "n4").props.percent, 30, "expand: literal restored from the call node");
        // errors
        eq(EL.collapseSelection(evening, cat, { n1: true, n2: true }, {}).code, "event", "events cannot be collapsed");
        eq(EL.collapseSelection(evening, cat, {}, {}).code, "empty", "empty selection");
        eq(EL.collapseSelection(evening, cat, { n2: true, n4: true }, {}).code, "multi_entry", "two entries/heads rejected");
        // pins from wires crossing the boundary: data in and out, typed
        var hp = D.gets.headphones.command;
        var r2 = EL.collapseSelection(hp, cat, { n2: true, n3: true }, { name: "X" });
        ok(r2.ok, "collapse headphones n2+n3");
        eq(r2.fn.inputs.map(function (p) { return [p.id, p.type]; }), [["device", "text"], ["percent", "int"]], "inputs inferred with types (wire + numeric literal)");
        eq(r2.plan.inputs, [{ pin: "device", from: ["n1", "device"] }], "plan: the wired input remembers its outside source");
        var ap2 = EL.applyCollapse(hp, r2.plan, "fn.x@1");
        eq(wires(ap2.cmd, "n1", "device").map(function (w) { return w.to; }), [[ap2.id, "device"]], "data wire re-joined to the call node");
        eq(wires(ap2.cmd, ap2.id, "exec_out").map(function (w) { return w.to; }), [["n4", "exec_in"]], "exit exec wire re-joined");
        // pure-only group: a function without execution pins
        var pm = EL.addNode(hp, cat["convert.to_text@1"], 100, 600), pm2 = EL.addNode(pm.cmd, cat["convert.to_int@1"], 400, 600);
        var pc = EL.connect(pm2.cmd, cat, [pm.id, "text"], [pm2.id, "text"]);
        var r3 = EL.collapseSelection(pc, cat, (function () { var o = {}; o[pm.id] = true; o[pm2.id] = true; return o; })(), { name: "P" });
        eq([r3.ok, r3.fn.exec], [true, false], "a group of data nodes becomes a pure function");
        eq(r3.fn.outputs, [], "no outside consumers: no outputs");
        // the interface nodes of a function graph are protected
        var gr = { nodes: [{ id: "fn_in", type: "function.input@1", pos: [0, 0], props: {} }, { id: "n1", type: "action.notify@1", pos: [10, 10], props: {} }], wires: [] };
        eq(EL.deleteItems(gr, { nodes: { fn_in: true, n1: true }, wires: {}, comments: {} }).nodes.map(function (n) { return n.id; }), ["fn_in"], "interface nodes cannot be deleted");
        // palette hides events inside functions and the function itself
        ok(EL.searchCatalog(cat, "закат", 10, { noEvents: true }).length === 0, "palette: no events inside a function");
        ok(EL.searchCatalog(cat, "тихий вечер", 10, { exclude: "fn.quiet-evening@1" }).length === 0, "palette: a function is not offered inside itself");
        ok(EL.searchCatalog(cat, "тихий вечер", 10).length === 1, "palette: the function is in the palette");
    }

    // ---- debug overlay reducer (DebugLogic.js): hand-written streams + the real recorded rehearsals
    function ev(e, seq, extra) { return Object.assign({ v: 1, seq: seq, ev: e, run: "1-1", t: seq / 100 }, extra); }
    function debugLogic() {
        var st = DL.reduce(DL.create(), { ev: "run.start", run: "1-1", cmd: "c", name: "C", rehearse: true });
        eq([st.live, st.rehearse, st.status], [true, true, "running"], "run.start resets the state");
        var evs = [ev("enter", 1, { node: "a", type: "x@1" }), ev("exit", 2, { node: "a", pins: { t: "hi", n: 3 }, dur: 0.5, out_pin: "then" }),
                   ev("wire", 3, { exec: true, from: ["a", "then"], to: ["b", "exec_in"] }), ev("skip", 4, { node: "z", via: ["a", "else"] }),
                   ev("wire", 5, { from: ["a", "t"], to: ["b", "title"], value: "hi" }),
                   ev("enter", 6, { node: "b", type: "y@1" }), ev("var", 7, { name: "g", value: "x" }),
                   ev("error", 8, { node: "b", error: "Сломалось", pins: { title: "hi" }, dur: 0.1 })];
        st = DL.reduceAll(st, evs);
        eq([st.nodes.a.state, st.nodes.b.state, st.nodes.z.state], ["ok", "error", "skipped"], "node states");
        eq(DL.badge(st.nodes.b.state), "error", "badge kind");
        eq(Object.keys(st.wires).sort(), ["a:t>b:title", "a:then>b:exec_in"], "wire keys");
        eq([st.wires["a:t>b:title"].value, st.wires["a:then>b:exec_in"].exec], ["hi", true], "wire value / exec flag");
        eq(st.vars, { g: "x" }, "variables");
        eq([st.error.node, st.error.message], ["b", "Сломалось"], "error panel data");
        eq(st.steps.map(function (s) { return s.status; }), ["ok", "skipped", "error"], "timeline statuses");
        eq(DL.filterSteps(st.steps, true).length, 1, "errors-only filter");
        eq(st.steps[0].summary, "t = «hi» · n = 3", "step summary");
        st = DL.reduce(st, { ev: "run.end", status: "err", message: "Сломалось", failed_node: "b", dur: 0.6 });
        eq([st.live, st.status, st.failed], [false, "err", "b"], "run.end");
        // pause / resume and loop iterations
        var p = DL.reduceAll(DL.create("2-1"), [ev("pause", 1, { node: "n", reason: "breakpoint" })]);
        eq([p.paused.node, p.nodes.n.state], ["n", "paused"], "pause marks the node");
        p = DL.reduce(p, ev("resume", 2, { node: "n", action: "step" }));
        eq([p.paused, p.nodes.n.state], [null, ""], "resume clears the pause");
        var l = DL.reduceAll(DL.create("3-1"), [ev("iter", 1, { node: "f", index: 1, total: 3 }), ev("enter", 2, { node: "n", iter: [1] })]);
        eq([l.nodes.f.loop, l.nodes.n.iter, l.steps[0].iter], [{ index: 1, total: 3 }, [1], [1]], "loop iteration index");
        // the loop runs a node twice: the last pin values win, run count grows
        var r = DL.reduceAll(DL.create("4-1"), [ev("enter", 1, { node: "n" }), ev("exit", 2, { node: "n", pins: { a: 1 } }), ev("enter", 3, { node: "n" }), ev("exit", 4, { node: "n", pins: { a: 2 } })]);
        eq([r.nodes.n.runs, r.nodes.n.pins.a, r.steps.length], [2, 2, 2], "node run counter");
        // a stale seq never rewinds, an unknown event is ignored
        eq(DL.reduce(r, { ev: "mystery" }).seq, 4, "unknown events are ignored");
        // bounded timeline
        var big = DL.create("5-1");
        for (var i = 0; i < DL.MAX_STEPS + 50; i++) big = DL.reduce(big, ev("enter", i + 1, { node: "n" + (i % 7) }));
        eq(big.steps.length, DL.MAX_STEPS, "timeline is bounded");
        eq(DL.tooltipRows({ error: "e", pins: { a: true, b: [1] } }), [{ k: "error", v: "e" }, { k: "a", v: "да" }, { k: "b", v: "[1]" }], "tooltip rows");
        // real recorded rehearsals: every wire the engine reports exists in the command, every entered node is known
        var names = Object.keys(D.traces), checked = 0;
        for (var k = 0; k < names.length; k++) {
            var rec = D.traces[names[k]], cmd = D.gets[names[k]].command, s2 = DL.fromTrace(rec);
            var wkeys = cmd.wires.map(function (w) { return EL.wireKey(w); });
            Object.keys(s2.wires).forEach(function (key) { checked++; ok(wkeys.indexOf(key) >= 0, names[k] + ": traced wire " + key + " is in the command"); });
            Object.keys(s2.nodes).forEach(function (id) { ok(EL.findNode(cmd, id) !== null, names[k] + ": traced node " + id + " is in the command"); });
            ok(!s2.live && s2.rehearse === true && s2.status === rec.status, names[k] + ": loaded trace is finished");
            ok(s2.steps.length > 0, names[k] + ": timeline is not empty");
        }
        ok(names.length > 0 && checked > 0, "recorded traces were compared (" + names.length + " commands, " + checked + " wires)");
    }

    function tutorial() {
        var steps = D.tutorial.steps, st = EL.tutState(D.tutorial.state);
        ok(steps.length >= 6 && steps.length <= 8, "tutorial has 6-8 steps");
        ok(EL.tutOffer(st), "first launch: the tutorial is offered");
        st = EL.tutStart();
        eq([st.active, st.step], [true, 0], "start");
        ok(!EL.tutOffer(st), "no offer while running");
        // events that do not match the current step change nothing
        eq(EL.tutAdvance(st, steps, { kind: "saved" }), st, "wrong event ignored");
        eq(EL.tutAdvance(st, steps, { kind: "node_added", type: "action.notify@1" }), st, "node event ignored on the first step");
        st = EL.tutAdvance(st, steps, { kind: "command_created" });
        eq(st.step, 1, "command created -> step 2");
        eq(EL.tutAdvance(st, steps, { kind: "command_created" }).step, 1, "an event does not advance twice");
        st = EL.tutNext(st, steps);            // the «event» step is read-only: «Далее»
        eq(st.step, 2, "next");
        eq(EL.tutAdvance(st, steps, { kind: "node_added", type: "action.shell@1" }).step, 2, "a different node does not match");
        st = EL.tutAdvance(st, steps, { kind: "node_added", type: "action.notify@1" });
        eq(st.step, 3, "notify node added -> wire step");
        eq(EL.tutAdvance(st, steps, { kind: "wire_added", exec: false }).step, 3, "a data wire is not an execution wire");
        st = EL.tutAdvance(st, steps, { kind: "wire_added", exec: true });
        eq(st.step, 4, "exec wire -> data step");
        st = EL.tutAdvance(st, steps, { kind: "wire_added", exec: false });
        eq(st.step, 5, "data wire -> rehearsal step");
        st = EL.tutBack(st, steps);
        eq(st.step, 4, "back");
        st = EL.tutAdvance(EL.tutNext(st, steps), steps, { kind: "rehearsed" });
        eq(st.step, 6, "rehearsed -> save step");
        st = EL.tutAdvance(st, steps, { kind: "saved" });
        eq([st.active, st.done, st.skipped], [false, true, false], "saved finishes the tutorial");
        ok(!EL.tutOffer(st), "no offer after finishing");
        eq(EL.tutAdvance(st, steps, { kind: "saved" }), st, "finished tutorial ignores events");
        eq(EL.tutBack(EL.tutStart(), steps).step, 0, "back stops at the first step");
        var sk = EL.tutSkip(EL.tutNext(EL.tutStart(), steps));
        eq([sk.active, sk.skipped, sk.done], [false, true, false], "skip");
        ok(!EL.tutOffer(sk), "no offer after skip");
        eq(EL.tutPersist({ active: true, step: 3, done: false, skipped: false }), ["tutorial", "set", "--step", "3", "--done", "0", "--skipped", "0"], "persist args");
        ok(EL.tutOffer(EL.tutState({ step: 2 })) && EL.tutState({ step: 2 }).step === 2, "saved progress is restored");
        ok(!EL.tutOffer(EL.tutState({ done: true })), "a finished tutorial is not offered again");
        ok(EL.tutMatch("node_added:event.*", { kind: "node_added", type: "event.sun@1" }), "wildcard rule");
        ok(!EL.tutMatch("node_added:event.*", { kind: "node_added", type: "action.notify@1" }), "wildcard rule miss");
        // every rule of the real tutorial matches the event it names
        for (var i = 0; i < steps.length; i++) {
            var r = steps[i].advance.split(":");
            ok(r[0] === "next" || EL.tutMatch(steps[i].advance, { kind: r[0], type: r[1] ? r[1].replace("*", "x") + "@1" : "", exec: r[1] === "exec" }), "step " + i + " rule is satisfiable: " + steps[i].advance);
        }
    }
    function galleryComments() {
        var g = D.gets["gallery-focus-25"];
        ok(g.comments.length === 4 && g.comments[0].title === "Запуск", "gallery comments are localized by the engine");
        var en = EL.buildView(g.command, cat, "en", null);
        ok(en.comments[0].title === "Start" && en.comments[1].text.indexOf("Do-not-disturb") === 0, "the editor view picks the language of {ru, en} comments");
        var ru = EL.buildView(g.command, cat, "ru", null);
        eq(ru.comments[0].title, "Запуск", "ru comment");
    }

    Component.onCompleted: {
        tutorial();
        galleryComments();
        debugLogic();
        parity();
        ops();
        fnCollapse();
        console.log("RESULT passed=" + passed + " failed=" + failed);
        Qt.exit(failed > 0 ? 1 : 0);
    }
}
